### ISSUE TITLE
Use github actions to automatically sync packages to AUR

### ISSUE THREAD

**Issue by petronny** [rocm-arch/rocm-arch#251]
To achieve this, you need:
* A file called `.github/workflows/sync.yml`
and it runs on every push event
* Store credit in `Settings > Secrets`
like `AUR_SSH_KEY`
* save the credit file (it won't be exposed in the log)
```yaml
  - run: echo ${{ secret.AUR_SSH_KEY }} > ~/.ssh/id_rsa
    env:
      AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
```
* Determine which packages to sync from the commit changes. Then sync them to AUR.
```yaml
  - run: apt-get install git # Make sure git is installed before checkout
  - uses: action/checkout@v2
  - run: |
      for i in $(git show --pretty="" --name-only | cut -d/ -f1 | uniq)
      do
        git show $i > ~/$i.patch
        git clone ssh://aur@aur.archlinux.org/$i.git ~/$i
        (cd ~/$i; git am -p1 ~/$i.patch; git push origin master)
        rm -rf ~/$i
      done
```
